//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Wishlist_app.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Compare = System.Web.Mvc.CompareAttribute;

    public partial class Family
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Provide Name", AllowEmptyStrings = false)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Provide at least the Address1", AllowEmptyStrings = false)]
        public string Address1 { get; set; }
        public string Address2 { get; set; }

        [Required(ErrorMessage = "Please Provide City", AllowEmptyStrings = false)]
        public string City { get; set; }

        [Required(ErrorMessage = "Please Provide Country", AllowEmptyStrings = false)]
        public string Country { get; set; }

        [Required(ErrorMessage = "Please Provide Zipcode", AllowEmptyStrings = false)]
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int ChildAmount { get; set; }

        [Required(ErrorMessage = "Please Provide Password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50, MinimumLength = 8, ErrorMessage = "Password must be 8 characters long")]
        public string Password { get; set; }


        [Compare("Password", ErrorMessage = "Confirm Password is not Match")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}

