//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Wishlist_app.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class WishList
    {
        public Nullable<int> Amount { get; set; }
        public string Status { get; set; }

        [Key]
        [Column(Order = 0)]
        public int ChildId { get; set; }

        [Key]
        [Column(Order = 1)]
        public string ItemASIN { get; set; }
    }
}
